# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 5e0cbcdc2c7c543c2a52b0cd22d45bcc7d61ae71fadc94e6edf98cdefbe6b6389af494da132b3ade464a737b59b016d492333f34e56d7e518206a152d032c7de

test:
  secret_key_base: bce07896466c047bf0a8ac2a886c3be30431071c22ca00a5d8489875d725d7473c11784abb8049e3ebdcecf78f5dc7d4a2adc0659d9edc1a2a53855b59aafa34

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
